### ISSUE TITLE
PaginationServiceProvider.php > register() > singleton

### ISSUE THREAD

**Issue by seltix5** [AgelxNash/SEOPagination#10]
hi,
after 3 days searching for a problem using multiple DB connection i finnaly found the root problem here :

https://github.com/AgelxNash/SEOPagination/blob/laravel-5.1/src/PaginationServiceProvider.php#L35

because the "registar" functions uses "singleton" when i try to create a new connection L5.2 always returns the previous connection...

solution for this please?

maybe change "singleton" to "bind" ?

thanks

**Comment by AgelxNash** [comment]
Yes, you can submit PR?

**Comment by seltix5** [comment]
What is PR?

**Comment by AgelxNash** [comment]
Pull Request

**Comment by seltix5** [comment]
Sure

**Comment by seltix5** [comment]
Done 
https://github.com/AgelxNash/SEOPagination/pull/11

I don't know if I create it correctly, github is a bit confusing when creating a PR :-\

**Comment by AgelxNash** [comment]
thx
