### ISSUE TITLE
error config

### ISSUE THREAD

**Issue by WaterSpout** [AgelxNash/SEOPagination#3]
i have error on command `php artisan vendor:publish` — `Can't locate path: </var/www/laravel/vendor/agelxnash/seopagination/src/../config/seo-pagination`.

Bug in `PaginationServiceProvider`, switch `$configPath = __DIR__.'/../config/seo-pagination';` on `$configPath = __DIR__.'/../config/seo-pagination.php';`

**Comment by AgelxNash** [comment]
Thanks. Done: https://github.com/AgelxNash/SEOPagination/commit/c2df73076487ca84a966692c689196a0d9ee72ba
