### ISSUE TITLE
Replace pagination in \Illuminate\Database\Query\Builder

### ISSUE THREAD

**Issue by Gael42** [AgelxNash/SEOPagination#5]
When using paginate() with HAVING clause like this :

```
$radius = 100;
$distance_field = '( 3959 * acos( cos( radians( '.$coords['latitude'].' ) ) * cos( radians( `lat` ) ) * cos( radians( `long` ) - radians( '.$coords['longitude'].' ) ) + sin( radians( '.$coords['latitude'].' ) ) * sin( radians( `lat` ) ) ) ) AS distance';

$items = DB::table('items')
            ->leftJoin('associated_items', 'items.associated_items_id', '=', 'associated_items.id')
            ->select(DB::raw($distance_field.', items.id, items.name'))
            ->having('distance', '<=', $radius)
            ->orderBy('distance')
            ->paginate(7);
```

I get the following error :

`QueryException in Connection.php line 636: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'distance' in 'having clause' (SQL: select count(*) as aggregate from `items` left join `associated_items` on `items`.`associated_items_id` = `associated_items`.`id` having `distance` <= 100)`

the same request with get() instead of paginate() works fine.

Thanks in advance :-)

**Comment by AgelxNash** [comment]
With standard provider Illuminate\Pagination\PaginationServiceProvider a similar situation?

**Comment by Gael42** [comment]
Yes exaclty the same, it looks like it has nothing to do with your package.

It's when the paginator try to execute a count(*) query to get page numbers, i did not find any workaround for now.

Since you know well pagination in laravel, is this a bug or a normal behaviour ? is there some mistake or bad practice in that code snippet in your opinion ?

**Comment by AgelxNash** [comment]
Look at https://github.com/laravel/framework/issues/3105 and http://stackoverflow.com/a/20945960

**Comment by Gael42** [comment]
Thanks a lot ! i had found those ones, but i still can't believe laravel does not offer a way to handle it properly in a genreic way... my first real disapointment about this totally awesome framework :-)

**Comment by Gael42** [comment]
I found a pretty nice workaround, at least it fit my needs so i just leave this here :

this permit to use raw **HAVING clause** (_for Haversine formula in this case_) and native or extended with AgelxNash/SEOPagination **simplePaginate()** and working with fully hydrated **Eloquent Collections**.  ( it does not work for paginate() with page numbers ) :

```
        $radius = 200;
        $coords = User::getCurrentCoordinates($request);

        // get activities paginated an orderer by distance
        $distance_field = '( 6371* acos( cos( radians( '.$coords['latitude'].' ) ) * cos( radians( `lat` ) ) * cos( radians( `long` ) - radians( '.$coords['longitude'].' ) ) + sin( radians( '.$coords['latitude'].' ) ) * sin( radians( `lat` ) ) ) ) AS distance';
        $nearest_activities = DB::table('activities')
            ->leftJoin('providers', 'activities.provider_id', '=', 'providers.id')
            ->select(DB::raw('activities.id, '.$distance_field))
            ->having('distance', '<=', $radius)
            ->orderBy('distance')
            ->simplePaginate(7);

        // creating an array to keep the order and the distance from user for those activities
        $activity_geodata_tab = [];
        foreach ($nearest_activities as $activity_geodata)
          $activity_geodata_tab[$activity_geodata->id] = $activity_geodata->distance;

        // retrieving activities via Eloquent with an array of id's and IN operator
        // order by FIELD(id, id_value1, id_value2, ...) permit to order results as in the first query
        $activities = Activity::with('activity_type')
            ->whereIn('id', array_keys($activity_geodata_tab))
            ->orderByRaw('FIELD(id, '.implode(',', array_keys($activity_geodata_tab)).')')
            ->get();

        // check if the page exixsts with AgelxNash/SEOPagination checkPaginate()
        // include full results for hydrated models
        // include paginated results to conserve Paginator
        // include generated geodata array for keeping ditance
        if(($out = $nearestActivities['paginated_results']->checkPaginate()) === true)
        {
            $out = view('home')
                ->with('activities', $nearestActivities['activities'])
                ->with('paginated_results', $nearestActivities['paginated_results'])
                ->with('activities_geodata', $nearestActivities['activities_geodata'])
                ->with('activities_wtf', $activities_wtf);
        }

        return $out;
```

It only execute two minimalist queries, the first to find the nearest items with the Haversine formula which give only, ids, distance and order, and the second executed to hydrate the Eloquent collection.

**I didn't find the `checkPaginate()` equivalent for `simplePaginate()` in your package... is there one ?** it seems to be implemented but i can't find where so i just replaced it with a `if($activities->isEmpty() !== true && $request->input('page') != 1)` that do the trick.

([edit] - i applied the checkPaginate() method in this code snippet since it was fidex by @AgelxNash)

**Comment by AgelxNash** [comment]
https://github.com/AgelxNash/SEOPagination/blob/laravel-5.1/src/Eloquent/Builder.php#L39-L51
You have connected the AgelxNash\SEOPagination\PaginationServiceProvider after the test?

**Comment by Gael42** [comment]
I think so, sorry if i dont understand what you ask, but with your package as PaginationProvider
i can do :

```
$results = $queryBuilder->paginate(5);
if ($result->checkPaginate())
{ /* do stuff */}
```

but not

```
$results = $queryBuilder->simplePaginate(5);
if ($result->checkPaginate())
{ /* do stuff */}
```

it results in `Call to undefined method Illuminate\Database\Eloquent\Collection::checkPaginate()`

**Comment by AgelxNash** [comment]
Thank you for your feedback.

``` php
$q = \App\Models\Setting::orderBy('name', 'DESC')->paginate(3);
$q->checkPaginate();

$q = \App\Models\Setting::orderBy('name', 'DESC')->simplePaginate(3);
$q->checkPaginate();

$q = DB::table((new \App\Models\Setting)->getTable())->orderBy('name', 'DESC')->paginate(3);
$q->checkPaginate();

$q = DB::table((new \App\Models\Setting)->getTable())->orderBy('name', 'DESC')->simplePaginate(3);
$q->checkPaginate();
```

**Comment by Gael42** [comment]
Thank YOU for fixing it so fast, it works perfectly now, i edited my precedent snippet to fit with your patch.
